CREATE TABLE projects
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title         VARCHAR(255),
    description   VARCHAR(255),
    rating        DOUBLE PRECISION,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    duration_days INTEGER,
    CONSTRAINT pk_projects PRIMARY KEY (id)
);